Titanic dataset is one of the datasets available in sklearn. You are given:

1. A Training dataset csv file with X train and Y train data
2. A X test File and you have to predict and submit predictions for this file.


Your task is to:

- Use Logistic Regression and come with predictions.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("0000000000002429_training_titanic_x_y_train.csv")
df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [3]:
df.shape

(668, 11)

In [4]:
df.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [5]:
df.isnull().sum()

Pclass        0
Name          0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [6]:
#replace null value with mean value
df.Age.fillna(df.Age.mean(),inplace=True)
df.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  668.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   12.753571    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   23.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.700560    0.000000    0.000000   14.750000    0.000000
75%      3.000000   35.000000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [7]:
def f1(s):
    if s=='female':
        return 0
    else:
        return 1

def f2(s):
    if s=='S':
        return 1
    elif s=='Q':
        return 2
    else:
        return 3
def f3(s):
    return s

In [8]:
df["sex_numeric"]=df.Sex.apply(f1)
df["Embarked_numeric"]=df.Embarked.apply(f2)
df["Survived_numeric"]=df.Survived.apply(f3)
del df["Name"]
del df["Cabin"]
del df["Sex"]
del df["Embarked"]
del df["Ticket"]
del df["Fare"]
del df["Survived"]
df.head()

Pclass       Age  SibSp  Parch  sex_numeric  Embarked_numeric  \
0       2  29.00000      1      0            0                 1   
1       3  29.70056      0      0            1                 1   
2       2  39.00000      0      0            1                 1   
3       3  29.00000      0      4            0                 1   
4       3  25.00000      0      0            1                 1   

   Survived_numeric  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [9]:
df.dtypes

Pclass                int64
Age                 float64
SibSp                 int64
Parch                 int64
sex_numeric           int64
Embarked_numeric      int64
Survived_numeric      int64
dtype: object

In [10]:
train_data=np.array(df,int)
train_data

array([[ 2, 29,  1, ...,  0,  1,  1],
       [ 3, 29,  0, ...,  1,  1,  0],
       [ 2, 39,  0, ...,  1,  1,  0],
       ...,
       [ 3, 32,  0, ...,  1,  1,  1],
       [ 3, 22,  0, ...,  0,  1,  0],
       [ 3, 29,  1, ...,  0,  2,  1]])

In [11]:
x_train=train_data[:,:-1]
y_train=train_data[:,-1]
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
#train the classifier
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
df2=pd.read_csv("0000000000002429_test_titanic_x_test.csv")
print(df2.shape)
df2.describe()

(223, 10)


Pclass         Age       SibSp       Parch        Fare
count  223.000000  178.000000  223.000000  223.000000  223.000000
mean     2.345291   29.694775    0.506726    0.304933   32.622551
std      0.850047   15.398053    1.169700    0.634108   61.062047
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   19.250000    0.000000    0.000000    7.879200
50%      3.000000   27.000000    0.000000    0.000000   12.475000
75%      3.000000   37.750000    1.000000    0.000000   30.035400
max      3.000000   71.000000    8.000000    2.000000  512.329200

In [13]:
df2.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [14]:
df2.Age.fillna(df2.Age.mean(),inplace=True)
df2["sex_numeric"]=df2.Sex.apply(f1)
df2["Embarked_numeric"]=df2.Embarked.apply(f2)
del df2["Name"]
del df2["Sex"]
del df2["Embarked"]
del df2["Cabin"]
del df2["Ticket"]
del df2["Fare"]
df2.head()

Pclass        Age  SibSp  Parch  sex_numeric  Embarked_numeric
0       2   8.000000      1      1            1                 1
1       1  49.000000      0      0            0                 1
2       3  29.694775      0      0            1                 2
3       2  24.000000      2      1            0                 1
4       1  36.000000      0      0            1                 1

In [15]:
test_data=np.array(df2,int)
test_data

array([[ 2,  8,  1,  1,  1,  1],
       [ 1, 49,  0,  0,  0,  1],
       [ 3, 29,  0,  0,  1,  2],
       ...,
       [ 1, 17,  1,  0,  0,  3],
       [ 3, 43,  0,  0,  1,  1],
       [ 2, 36,  0,  2,  1,  1]])

In [16]:
x_test=test_data[:,:]
y_pred=clf.predict(x_test)

In [17]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0])

In [18]:
y_pred=y_pred.reshape(-1,1)

In [19]:
np.savetxt("output_logistic_titanic.csv",y_pred)